# Server config
server:
  port: 8999

logging:
  level:
    ROOT: ERROR
    org.springframework.web: DEBUG

info:
  component: API Gateway

spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        discovery.locator:
          enabled: true
          lowerCaseServiceId: true
        routes:
          - id: oauth
            uri: lb://AUTH-SERVER
            predicates:
              - Path=/**

# Eureka config
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

# Ribbon config
ribbon:
  eureka:
    enabled: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
