server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
  oauth2:
    client:
      access-token-validity-seconds: 1800
      authorized-grant-types: password,refresh_token
      client-id: coderef
      client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
      resource-ids: evolum-resource-id
      scope: read,write

spring:
  datasource:
    platform: postgres
    # data: classpath:/sql/data.sql
    # schema: classpath:/sql/schema.sql
    driver-class-name: org.postgresql.Driver
    # initialization: always
    url: jdbc:postgresql://localhost:5432/evoluum
    password: codenation
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true

hibernate:
  temp:
    use_jdbc_metadata_defaults: false

# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'

logging:
  level:
    org:
      springframework:
        web: DEBUG
